{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    {{- with .Values.platform.component }}
    platform.taskapp.io/component: {{ . | quote }}
    {{- end }}
    {{- with .Values.platform.environment }}
    platform.taskapp.io/environment: {{ . | quote }}
    {{- end }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
{{- end }}
